include: package:flutter_lints/flutter.yaml

# Feel free to enable a stricter analysis configuration.
# The basic, but useful one following can be uncommented:
# To learn more, check out https://dart.dev/tools/analysis.
#
#analyzer:
#  language:
#    strict-casts: true
#    strict-inference: true
#    strict-raw-types: true
#
#linter:
#  rules:
#    - always_declare_return_types
#    - avoid_dynamic_calls
#    - omit_local_variable_types
#    - prefer_single_quotes
#    - type_annotate_public_apis
#    - unawaited_futures
